name: Build_CI

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: Name of the plugin / binary.
        required: false
        default: "ReHopper"

      version:
        description: The release version tag to be included in the name.
        required: true
        default: v0.0.1-alpha

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      
      - name: Checkout Repo
        uses: actions/Checkout@v3
      
      - name: Build Plugin
        id: build-plugin
        uses: thekaushikls/make-ghpy@v1
        with:
          source: src
          package-name: ${{ github.event.inputs.package-name }}
          version: ${{ github.event.inputs.version }}
          ironpython: true
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build-plugin.outputs.name }}
          path: ${{ steps.build-plugin.outputs.build }}
          if-no-files-found: error
